# Based on http://conda.pydata.org/docs/travis.html
language: python
sudo: false # use container based build
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  - python: 2.6
    env: UPDATE_ENV="conda install unittest2 pandas==0.15.0"
  # Test on Python 2.7 with and without netCDF4/scipy/cdat-lite
  - python: 2.7
    env: UPDATE_ENV="pip install cyordereddict && conda install -c ajdawson cdat-lite"
  - python: 2.7
    # nb. we have to remove scipy because conda install pandas brings it in:
    # https://github.com/ContinuumIO/anaconda-issues/issues/145
    env: UPDATE_ENV="conda remove scipy netCDF4"
  - python: 3.3
  - python: 3.4
    env: UPDATE_ENV="pip install cyordereddict"
  # don't require pydap tests to pass because the dap test server is unreliable
  - python: 2.7
    env: UPDATE_ENV="pip install pydap"
  allow_failures:
  - python: 2.7
    env: UPDATE_ENV="pip install pydap"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create --yes -n test_env python=$TRAVIS_PYTHON_VERSION pip nose numpy pandas scipy netCDF4
  - source activate test_env
  - echo $UPDATE_ENV; eval $UPDATE_ENV
  - python setup.py install

script:
  - nosetests
